### ISSUE TITLE
Install does not create admin user.

### ISSUE THREAD

**Issue by macromorgan** [catborise/webvirtcloud#1]
When I follow the installation method (substituting your git repository for the main one) everything works just fine, except the default user of admin does not get created.

Tested on Ubuntu 20.04 with Python 3.

**Comment by catborise** [comment]
@macromorgan thanks. it will be fixed. i missed it

for now you can create it manually.

set venv, then;
python3 manage.py createsuperuser

**Comment by macromorgan** [comment]
Thank you, your latest commits fixes this.  I'm doing a test install of Ubuntu Server 20.04 inside of a VM on Ubuntu Server 20.04 inside of a VM on Debian 10.3 now.  :-)  Ubuntu 20.04 completely dropped support for Python 2, so it's time to find something that runs python 3.
