### ISSUE TITLE
Merge latest changes from Real-Gecko repository

### ISSUE THREAD

**Issue by lord-kyron** [catborise/webvirtcloud#2]
hi @catborise 
there is another contributor to retspen webvirtcloud original project called Real-Gecko
Can you please adopt and merge his latest changes, as there are some pretty useful stuff there and I am using the docker image from your repo?
Thanks!

**Comment by catborise** [comment]
@lord-kyron i am making big changes this makes me busy(bootstrap 4.5, theme selection, settings page).
and there are many confilict with real-geckos commit.
i must merge them... give me some time

**Comment by lord-kyron** [comment]
@catborise - yes, of course! Thank you! I don't need it fast, just wanted to tell you to merge them at some point. It will be great to have them in your repo!
Thanks once again!
