### ISSUE TITLE
Problem after latest update

### ISSUE THREAD

**Issue by lord-kyron** [catborise/webvirtcloud#3]
hi @catborise , I updated my docker image with the latest changes to the master branch I I cannot do makemigrations and migrate. I am always getting this same error as when I open the login page now:
![image](https://user-images.githubusercontent.com/39150122/83385732-6b8c6e80-a3f2-11ea-81b3-8c1d6d01e9e6.png)

**Comment by catborise** [comment]
@lord-kyron hi, compare settings.template and settings.py files.
add "admin" to installed apss in settings.py

**Comment by lord-kyron** [comment]
thanks, fixed
