### ISSUE TITLE
Error on theme change

### ISSUE THREAD

**Issue by lord-kyron** [catborise/webvirtcloud#4]
When I try to change theme after latest update, theme is not changing at all and in the "logs" sections I can see this error:
[Errno 13] Permission denied: 'dev/scss//wvc-main.scss'

**Comment by lord-kyron** [comment]
Yes, of course I did reload. But also I am not seeing the green bar on top saying that change has been applied as when I change some of the other options down.

**Comment by catborise** [comment]
could you please try it with bigchanges branch? (deploy with that branch
master branch a bit out of rail.

**Comment by catborise** [comment]
@lord-kyron problem is solved, isnt it?
