### ISSUE TITLE
VNC Lite console still not asking for password when set

### ISSUE THREAD

**Issue by lord-kyron** [catborise/webvirtcloud#7]
@catborise - I noticed that this issue is still present:
- when password for console is set, when I use Full VNC console, it asks me for password, but when I use the Lite VNC console on the same VM, it never asks for password and directly connects me.
Can you please fix this?

**Comment by catborise** [comment]
@lord-kyron i am sure i did control it... i will control it again.

**Comment by catborise** [comment]
@lord-kyron i check it again. it works as expected.
it does not as for superuser but others.

**Comment by lord-kyron** [comment]
@catborise - ok, I understand the logic - seems fine for superusers, but why then it asks for password in the full console? 
If I am superuser it shouldn't ask for password at all, not - ask in one place, but the other - not.

**Comment by catborise** [comment]
@lord-kyron  no it does not asking. you can click button to login. as you see password field not empty.

**Comment by lord-kyron** [comment]
@catborise - see what I see:
![vncpass](https://user-images.githubusercontent.com/39150122/90643226-051e2c00-e23c-11ea-8d65-9adcbd571d6f.gif)
You mean, that when I am superuser the password is filled in the password field automatically?

**Comment by lord-kyron** [comment]
Ah, ok then, thank you!
