### ISSUE TITLE
Insert IP address info into instances main page

### ISSUE THREAD

**Issue by lord-kyron** [catborise/webvirtcloud#8]
@catborise - I think it would be nice to have a "i" icon next to each instance name in the allinstances main page and when you click it to viwe the IP addresses (only ipv4 and ipv6 currently assigned to the machine).
I imagine it something like the "i" icon in the instance Settings -> Disks page:
![image](https://user-images.githubusercontent.com/39150122/90727217-95578200-e2cb-11ea-8a81-1c30257573c3.png)

Would this possible to do? It will save a lot more time when trying to find some VM IP and don't want to click across all menus to check it.

**Comment by catborise** [comment]
do you know phpipam? it is very useful for ip tracking. subnet listing. and monitoring ips & owner etc.
adding for all instances is very expensive operation.

**Comment by lord-kyron** [comment]
I know it and I use it actually. I juat thought that it can be useful to have the ips there also. If it os so expensive, fair enough.
